plugins {
    id 'com.android.application'
}

android {
    namespace 'studio.sobrano.orgstaff'
    compileSdk 35

    defaultConfig {
        applicationId 'studio.sobrano.orgstaff'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '1.2.1'

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'org.jsoup:jsoup:1.18.3'
    testImplementation 'junit:junit:4.13.2'
}
